[package]
name = "listing-11-07-custom-failure-message"
version = "0.1.0"
authors = ["Sonal Ranjit <sranjit@bluecatnetworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
